const form=document.getElementById('form')
const statusEl=document.getElementById('status')
let currentStep=1
function showStep(n){const steps=document.querySelectorAll('.step');steps.forEach((s,i)=>{const isActive=i===n-1;s.classList.toggle('hidden',!isActive);if(isActive){s.setAttribute('aria-current','step');s.removeAttribute('aria-hidden')}else{s.removeAttribute('aria-current');s.setAttribute('aria-hidden','true')}})}
function validateStep(n){const stepEl=document.querySelector(`.step[data-step="${n}"]`);if(!stepEl)return true;stepEl.querySelectorAll('.invalid').forEach(el=>el.classList.remove('invalid'));let ok=true;const mark=el=>{if(el){el.classList.add('invalid');ok=false}};const needRadio=name=>{const sel=document.querySelector(`input[name="${name}"]:checked`);if(!sel){const fs=stepEl.querySelector(`input[name="${name}"]`)?.closest('fieldset');mark(fs)}};const needText=id=>{const el=document.getElementById(id);if(el&&!el.value.trim()){el.classList.add('invalid');ok=false}};if(n===1){const group=name=>{const sel=stepEl.querySelectorAll(`input[name="${name}"]:checked`);if(sel.length===0){const fs=stepEl.querySelector(`input[name="${name}"]`)?.closest('fieldset');mark(fs)}};group('objetivos_dor');group('objetivos_sono');group('objetivos_mental');group('objetivos_gastro');group('objetivos_neuro');group('objetivos_outros')}if(n===2){needRadio('ansiedade_freq');needRadio('anedonia_freq');needRadio('diagnostico_psiquiatrico');const d=document.querySelector(`input[name="diagnostico_psiquiatrico"]:checked`);if(d&&d.value==='Outro'){needText('diagnostico_psiquiatrico_outro')}}if(n===3){needRadio('tempo_adormecer');needRadio('qualidade_sono');needRadio('melhorar_sono')}if(n===4){needRadio('medicamentos_uso');const m=document.querySelector(`input[name="medicamentos_uso"]:checked`);if(m&&m.value==='Sim'){needText('medicamentos_quais')}const cs=Array.from(document.querySelectorAll('input[name="condicoes_saude"]:checked'));if(cs.length===0){const fs=stepEl.querySelector('input[name="condicoes_saude"]')?.closest('fieldset');mark(fs)}if(cs.some(i=>i.value==='Outro (especifique)')){needText('condicoes_saude_outro')}}if(n===5){needRadio('experiencia_cannabis');const v=document.querySelector(`input[name="experiencia_cannabis"]:checked`);if(v&&v.value.startsWith('Já usei')){needText('experiencia_cannabis_detalhes')}}if(n===6){needRadio('alimentacao');const a=document.querySelector(`input[name="alimentacao"]:checked`);if(a&&a.value==='Outro (especifique)'){needText('alimentacao_outro')}needRadio('atividade_fisica');needRadio('fuma');needRadio('alcool')}return ok}
const _origValidateStep=validateStep;validateStep=function(n){const r=_origValidateStep(n);if(!r)return false;if(n===4){const el=document.getElementById('exames_lab');if(el&&!el.value.trim()){el.classList.add('invalid');return false}}return true}
document.addEventListener('click',e=>{if(e.target&&e.target.id==='next'){if(!validateStep(currentStep)){statusEl.textContent='Responda as perguntas obrigatórias desta etapa';statusEl.classList.remove('success');statusEl.classList.add('error');return}const total=document.querySelectorAll('.step').length;if(currentStep<total){currentStep++;showStep(currentStep)}}if(e.target&&e.target.id==='back'){if(currentStep>1){currentStep--;showStep(currentStep)}}})
document.addEventListener('change',e=>{if(e.target&&e.target.name==='diagnostico_psiquiatrico'){const outro=document.getElementById('diagnostico_psiquiatrico_outro');if(e.target.value==='Outro'){outro.style.display='block'}else{outro.style.display='none';outro.value=''}}})
document.addEventListener('change',e=>{if(e.target&&e.target.name==='medicamentos_uso'){const q=document.getElementById('medicamentos_quais');if(e.target.value==='Sim'){q.style.display='block'}else{q.style.display='none';q.value=''}}})
document.addEventListener('change',e=>{if(e.target&&e.target.name==='condicoes_saude'){const outroOpt=Array.from(document.querySelectorAll('input[name="condicoes_saude"]')).some(i=>i.value==='Outro (especifique)'&&i.checked);const outro=document.getElementById('condicoes_saude_outro');if(outroOpt){outro.style.display='block'}else{outro.style.display='none';outro.value=''}}})
document.addEventListener('change',e=>{if(e.target&&e.target.name==='experiencia_cannabis'){const v=e.target.value;const d=document.getElementById('experiencia_cannabis_detalhes');if(v.startsWith('Já usei')){d.style.display='block'}else{d.style.display='none';d.value=''}}})
document.addEventListener('change',e=>{if(e.target&&e.target.name==='alimentacao'){const o=document.getElementById('alimentacao_outro');if(e.target.value==='Outro (especifique)'){o.style.display='block'}else{o.style.display='none';o.value=''}}})
showStep(1)
function getToken(){const u=new URL(window.location.href);return u.searchParams.get('token')||''}
function getChecked(n){return Array.from(document.querySelectorAll(`input[name="${n}"]:checked`)).map(i=>i.value)}
form.addEventListener('submit',async e=>{e.preventDefault();const total=document.querySelectorAll('.step').length;for(let s=1;s<=total;s++){if(!validateStep(s)){showStep(s);statusEl.textContent='Responda as perguntas obrigatórias';statusEl.classList.remove('success');statusEl.classList.add('error');return}}const token=getToken();if(!token){statusEl.textContent='Token inválido';statusEl.classList.remove('success');statusEl.classList.add('error');return}const objetivos={gerenciamento_da_dor:getChecked('objetivos_dor'),melhora_do_sono:getChecked('objetivos_sono'),saude_mental_emocional:getChecked('objetivos_mental'),conforto_gastrointestinal:getChecked('objetivos_gastro'),condicoes_neurologicas:getChecked('objetivos_neuro'),outros_objetivos_de_saude:getChecked('objetivos_outros')};const getRadio=(n)=>{const x=document.querySelector(`input[name="${n}"]:checked`);return x?x.value:''};const payload={answers:{queixa_principal:document.getElementById('queixa').value,historico_relevante:document.getElementById('historico').value,alergias:document.getElementById('alergias').value,objetivos,saude_mental_emocional_freq_ansiedade:getRadio('ansiedade_freq'),saude_mental_emocional_freq_anedonia:getRadio('anedonia_freq'),diagnostico_psiquiatrico:getRadio('diagnostico_psiquiatrico'),diagnostico_psiquiatrico_outro:document.getElementById('diagnostico_psiquiatrico_outro').value||'',sono_tempo_para_adormecer:getRadio('tempo_adormecer'),sono_qualidade:getRadio('qualidade_sono'),sono_melhoria_interesse:getRadio('melhorar_sono'),medicamentos_uso:getRadio('medicamentos_uso'),medicamentos_quais:document.getElementById('medicamentos_quais').value||'',condicoes_saude:getChecked('condicoes_saude'),condicoes_saude_outro:document.getElementById('condicoes_saude_outro').value||'',exames_laboratoriais:document.getElementById('exames_lab').value||'',experiencia_cannabis:getRadio('experiencia_cannabis'),experiencia_cannabis_detalhes:document.getElementById('experiencia_cannabis_detalhes').value||'',estilo_de_vida_ocupacao:document.getElementById('ocupacao').value||'',estilo_de_vida_alimentacao:getRadio('alimentacao'),estilo_de_vida_alimentacao_outro:document.getElementById('alimentacao_outro').value||'',atividade_fisica:getRadio('atividade_fisica'),fuma:getRadio('fuma'),alcool:getRadio('alcool')}};statusEl.textContent='Enviando...';statusEl.classList.remove('error','success');try{const r=await fetch(`/intake/${token}/response`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(j.status==='received'){statusEl.textContent='Respostas enviadas';statusEl.classList.remove('error');statusEl.classList.add('success')}else{statusEl.textContent='Falha ao enviar';statusEl.classList.remove('success');statusEl.classList.add('error')}}catch(_){statusEl.textContent='Erro de rede';statusEl.classList.remove('success');statusEl.classList.add('error')}})
